# Generated by Django 5.0.6 on 2024-06-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_program_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6 ')], max_length=100),
        ),
    ]
