# Generated by Django 5.0.6 on 2024-06-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_program_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='course',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='course',
            field=models.ManyToManyField(null=True, to='management.course'),
        ),
    ]
