# Generated by Django 5.0.6 on 2024-06-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_lecturer_course_lecturer_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='courses',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.course'),
        ),
    ]
