# Generated by Django 5.0.6 on 2024-06-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_lecturer_courses_lecturer_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='courses',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='courses',
            field=models.ManyToManyField(to='management.course'),
        ),
    ]
